### ISSUE TITLE
Support of broadcom wifi card

### ISSUE THREAD

**Issue by p3nt4** [konklone/debian#10]
Hey,

Does this work for both wifi cards or only the intel one?

Cheers,
p3nt4

**Comment by konklone** [comment]
@p3nt4 I've only tried the WiFi card on the hardware model I bought, which is the XPS 13, with the default WiFi chip.

**Comment by p3nt4** [comment]
I think two versions of the XPS 13 exist, one with a broadcom chip and one with an intel chip.

**Comment by konklone** [comment]
I ran `lshw` on my machine just now - it looks like an Intel wireless card. Attached the output here:

[lshw.txt](https://github.com/konklone/debian/files/431752/lshw.txt)

**Comment by p3nt4** [comment]
Yeah, seems like it. 
Thanks for your answer. 
I think the ubunutu xps 13 comes with the intel card and the windows come with the broadcom one.
